### PR TITLE
Rework to use an enumeration

### PR DESCRIPTION
**Pull request by chikamichi**
Hi,

Following #1, I decided to battle-try my idea against the test suite. With minor refinements, all tests pass!

I think using an enumeration makes everything more descriptive, and easier to maintain. Especially `remove` doesn't need to handle a front `List` anymore.

### CODE REVIEW

**Comment by chikamichi** [comment]
By the way, separating the front value from the queue is certainly not mandatory. One could implement `Fifo` using a single list, as a "pipe":

``` elm
-- A Fifo of 'a' elements is just a List of 'a' elements.
-- It could be a type alias, but let's prefix it with the keyword 'Fifo'.
type Fifo a = Fifo (List a)

empty : Fifo a
empty = Fifo []

insert : a -> Fifo a -> Fifo a
insert a (Fifo fifo) =
  Fifo (fifo ++ [a])

remove : Fifo a -> (Maybe a, Fifo a)
remove (Fifo fifo) =
  case fifo of 
    [] -> (Nothing, empty)
    -- pattern matching works just fine!
    next :: rest -> (Just next, Fifo rest)

-- etc.
```

Food for thoughts.

**Comment by avh4** [comment]
Thanks for looking into this!

The new implementation here changes the runtime complexity of the the operations.  In the original version, `insert` is O(1), and `remove` is amortized O(1), since the reverse only happens one out of _n_ times.  In your version, `remove` is O(1), but `insert` is O(n).  I would expect typical usage of a FIFO to have a roughly equal number of inserts and removes, so I think keeping the amortized O(1) implementation is better.

The new functions look useful, though.  I'm not sure how hard it would be to add them to the two-list version.

**Comment by chikamichi** [comment]
Interesting. I fail to see why `insert` is O(n) though (in the PR's code), any insights?

_Edit_: more precisely, I'd expect `List.append` to be optimized down to O(1) since it inserts a _single_ value at the end of an array (no traversal or anything kinky). So even if [Elm's `append`](https://github.com/elm-lang/core/blob/3.0.0/src/List.elm#L274) is O(n) due to `foldr` merging two arrays, the latter of arbitrary size `n`, shouldn't it be considered a O(1) operation in the scope of this library, where only one value is ever going to be appended?

**Comment by avh4** [comment]
`append` is O(n), where _n_ is the size of the left-side list.  In `append xs ys`, it has to fold over the `xs`, not over the `ys`.  So unfortunately the number of items being appended makes no difference.

**Comment by chikamichi** [comment]
Ok, I understand now why you went for kind of a deque: constant access time for front and back.

I'm closing the PR and will think about how to best re-implement the other functions.

**Comment by avh4** [comment]
Cool.  In case you're curious, I found this thread about alternative fifo implementations: http://stackoverflow.com/questions/5538192/how-to-implement-a-queue-with-three-stacks

**Comment by chikamichi** [comment]
Thank you for sharing that (indeed) interesting link.

**Pull request closed without merging**
